apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "featbit.redis.conn.secretName" . }}
  labels:
    {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
type: Opaque
data:
  featbit-redis-config: {{ include "featbit.redis.config.3" . | b64enc | quote }}
  featbit-redis-url: {{ include "featbit.redis.url" . | b64enc | quote }}