apiExternalUrl: ""
evaluationServerExternalUrl: ""
autoDiscovery: true

ui:
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: featbitui


api:
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: featbitapi

els:
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: featbitels